"""
Text embeddings via Gemini's embedding API (OpenAI-compatible endpoint).

Previously this module loaded a local sentence-transformers model
(BAAI/bge-large-en-v1.5) directly into memory. That model, plus its
torch dependency, pushed backend memory well past Render's free-tier
512MB limit during deploy. Embeddings are now generated by calling
Gemini instead — nothing is loaded into local memory.

Gemini's gemini-embedding-001 model returns 3072-dimensional vectors
by default. The database's embedding_vector column is a fixed
vector(1024) (see models.py), so each embedding is truncated to its
first 1024 dimensions and re-normalized. gemini-embedding-001 is
trained with Matryoshka Representation Learning, which means a prefix
of the full vector is itself a valid, high-quality embedding — this is
Google's own documented approach for shrinking these embeddings, not
an improvised hack. It also sidesteps relying on the API's
output_dimensionality parameter, which has had inconsistent support
through some OpenAI-compatible integrations.

Calls are made one text at a time rather than batched, trading a
little speed for a call pattern that's certain to work against the
real endpoint.
"""

import numpy as np
from openai import OpenAI

from app.config import settings

embedding_client = OpenAI(
    api_key=settings.google_api_key,
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
)

EMBEDDING_MODEL = "gemini-embedding-001"
TARGET_DIM = 1024  # must match Vector(1024) in models.py


def _truncate_and_normalize(vector: list[float], dim: int = TARGET_DIM) -> list[float]:
    """Take the first `dim` values of a Matryoshka-trained embedding and
    re-normalize to unit length, so cosine distance in pgvector still
    behaves correctly."""
    arr = np.array(vector[:dim], dtype=np.float32)
    norm = np.linalg.norm(arr)
    if norm > 0:
        arr = arr / norm
    return arr.tolist()


def embed_chunks(texts: list[str]) -> list[list[float]]:
    """Embed a list of chunk texts. Same signature and behavior as
    before: returns one 1024-dim, L2-normalized vector per input
    string, in the same order.
    """
    results: list[list[float]] = []
    for text in texts:
        response = embedding_client.embeddings.create(
            model=EMBEDDING_MODEL,
            input=text,
        )
        results.append(_truncate_and_normalize(response.data[0].embedding))
    return results